# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-and-Test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build & Test
      env: 
        apikey: ${{ secrets.TMDBAPI }}
      run: dotnet build --no-restore
      working-directory: FilmLoggerDotNET
      shell: bash

    - name: Test
      run: dotnet test --no-build
      working-directory: FilmLoggerDotNET
      shell: bash
